[package]
name = "randd"
version = "0.1.0"

[dependencies]
rand_chacha = "0.2"
rand_core = "0.5"
redox_syscall = "0.1"
sha2 = "0.8"

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "2.0"
